/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        // Design system Struktura — colores exactos del DESIGN.md
        "outline":                    "#a38c7e",
        "on-primary-fixed-variant":   "#723600",
        "on-secondary-fixed":         "#001f25",
        "surface-container-high":     "#282a2d",
        "surface-bright":             "#37393d",
        "tertiary":                   "#f6ba8b",
        "surface":                    "#111316",
        "outline-variant":            "#554337",
        "on-primary-fixed":           "#311400",
        "surface-container-highest":  "#333538",
        "primary-fixed":              "#ffdcc6",
        "primary-fixed-dim":          "#ffb786",
        "on-secondary":               "#00363f",
        "surface-tint":               "#ffb786",
        "on-background":              "#e2e2e6",
        "on-tertiary-container":      "#432101",
        "surface-container":          "#1e2023",
        "tertiary-container":         "#bb855b",
        "on-surface":                 "#e2e2e6",
        "inverse-surface":            "#e2e2e6",
        "primary":                    "#ffb786",
        "on-secondary-container":     "#00404a",
        "on-error":                   "#690005",
        "error":                      "#ffb4ab",
        "secondary":                  "#4cd7f2",
        "surface-variant":            "#333538",
        "on-primary-container":       "#461f00",
        "tertiary-fixed-dim":         "#f6ba8b",
        "tertiary-fixed":             "#ffdcc3",
        "on-tertiary-fixed":          "#2f1500",
        "surface-container-low":      "#1a1c1f",
        "on-secondary-fixed-variant": "#004e5a",
        "on-error-container":         "#ffdad6",
        "background":                 "#111316",
        "inverse-primary":            "#964900",
        "on-primary":                 "#502400",
        "surface-dim":                "#111316",
        "surface-container-lowest":   "#0c0e11",
        "secondary-fixed-dim":        "#4cd7f2",
        "secondary-fixed":            "#a5eeff",
        "on-surface-variant":         "#dcc1b2",
        "primary-container":          "#da7726",
        "error-container":            "#93000a",
        "inverse-on-surface":         "#2f3034",
        "secondary-container":        "#00b3cd",
        "on-tertiary":                "#4b2705",
      },
      fontFamily: {
        sans: ["Inter", "sans-serif"],
      },
      borderRadius: {
        DEFAULT: "1rem",
        lg: "2rem",
        xl: "3rem",
        full: "9999px",
      },
    },
  },
  plugins: [],
};
